#!/bin/sh
#
# "VA SystemImager" - Copyright (C) 1999-2001 Brian Elliott Finley <brian@valinux.com>
#   Others who have contributed to this code (in alphabetical order):
#     dann frazier <dannf@ldl.fc.hp.com>
#     James Oakley <joakley@solutioninc.com>
#
#
# This file is: installclient
#   This script is a wrapper around the install_client_all rule in the
#   Makefile.  This takes care of upgrade issues and interacting with users.
#

# set some variables
COMMAND_PATH=`dirname $0`
test "x$COMMAND_PATH" != "x" && cd $COMMAND_PATH

if [ ! -f ./install_lib ]; then
  echo "Couldn't find ./install_lib, exiting."
  exit 1
fi  
. ./install_lib

### BEGIN introduction
# you sure you want to install?
echo -n "Install SystemImager client? (y/[n]) "
read REPLY
case $REPLY in
  y|Y|Yes|yes|YES ) clear; echo Ok.  Installing SystemImager client... ;;
                * ) echo Install cancelled.  No files installed. && exit 1 ;;
esac

echo
sleep 2
### END introduction ###

OLD_FILES="/usr/sbin/prepareclient /usr/sbin/updateclient /usr/sbin/lsimage"
remove_old_files

CONFIG_FILES="/etc/systemimager/updateclient.local.exclude:./tftpstuff/systemimager/updateclient.local.exclude"
upgrade_config_files

### BEGIN make install_client_all
echo "Running 'make install_client_all'..."
make install_client_all
if [ $? -ne 0 ]; then
    echo "Install failed - hopefully the messages above will help you debug the problem."
    exit 1
fi
### END make install_client_all
    
echo "You must run \"prepareclient\" before you can retrieve this clients image."
echo -n "Do you want to run \"prepareclient\" now? ([y]/n) "
read REPLY
case $REPLY in
  n|N|No|no|NO ) echo "\"prepareclient\" not run."
                 echo "Be sure to run \"prepareclient\" before you run \"getimage\" on the imageserver."
                 exit 0
                 ;;
  * ) prepareclient ;;
esac

exit 0
