#!/bin/sh

#
# "SystemImager" - Copyright (C) 1999-2000 Brian Elliott Finley <brian@valinux.com>
#

# do we want a quiet install? and do we want to run afterburner?
QUIET="false"
AFTERBURNER="yes"
for cl_option ; do
  case $cl_option in
    -q|-quiet|--quiet ) QUIET="true" ;;
    -n|-no-afterburner|--no-afterburner ) AFTERBURNER="no" ;;
  esac
done

# set some variables
PATH=/bin:/usr/bin:/sbin:/usr/sbin
COMMAND_PATH=`dirname $0`
test "x$COMMAND_PATH" != "x" && cd $COMMAND_PATH
INSTALL_DIR=`pwd`
VERSION=`cat $INSTALL_DIR/VERSION`
test "x$prefix" = "x" && prefix=/usr

# don't restart inetd unless necessary
RESTART_INETD=no

# if not run as root, install will surely fail
if [ "x$DESTDIR" = "x" ]; then
  [ `whoami` != "root" ] && echo "Must be run as root!" && exit 1
else
  mkdir -p $DESTDIR
  [ -d $DESTDIR -a -w $DESTDIR ] || exit 2
  mkdir -p ${DESTDIR}${prefix}/sbin
fi

# source needed functions
. $INSTALL_DIR/functions


### BEGIN introduction ###
if [ $QUIET = "false" ]; then
  clear
  echo "Welcome to SystemImager."
  echo
  echo "This install script may modify the following files and/or directories:"
  echo
  echo " /tftpboot/systemimager -- create if necessary and add appropriate files/links"
  echo " /tftpboot/pxelinux.cfg -- create if necessary and add appropriate files/links"
  echo " /etc/services          -- add rsync and/or tftp entries if necessary"
  echo " /etc/inetd.conf        -- add/modify rsync and tftp entries if necessary"
  echo " /etc/rsyncd.conf       -- it is assumed that SystemImager will manage this"
  echo "                           file and that it will not be used for anything else"
  echo
  echo " All modified files will be backed up with the .beforesystemimager extension."
  echo

  # you sure you want to install?
  echo -n "Install SystemImager? (y/[n]) "
  read REPLY
  case $REPLY in
    y|Y|Yes|yes|YES ) clear; echo Ok.  Installing SystemImager... ;;
                  * ) echo Install cancelled.  No files modified. && exit 1 ;;
  esac

  echo
  sleep 2
fi
### END introduction ###


### BEGIN binaries ###
for BINARY in `ls $INSTALL_DIR/sbin/ | grep -wv CVS`
do
  cp -af $INSTALL_DIR/sbin/$BINARY ${DESTDIR}${prefix}/sbin/
  [ "x$DESTDIR" = "x" ] && chown root:root ${prefix}/sbin/$BINARY
done
### END binaries ###


### BEGIN tftpboot stuff ###
# Create ${DESTDIR}/tftpboot/systemimager/ directory if necessary and copy/link files
if [ ! -d ${DESTDIR}/tftpboot/systemimager/ ]; then
  [ $QUIET = "false" ] && echo "Creating ${DESTDIR}/tftpboot/systemimager/..."
  mkdir -p ${DESTDIR}/tftpboot/systemimager/
else
  [ $QUIET = "false" ] && echo "${DESTDIR}/tftpboot/systemimager/ already exists..."
fi
[ $QUIET = "false" ] && echo "copying ${DESTDIR}/etc/hosts to ${DESTDIR}/tftpboot/systemimager/hosts..."
cd ${DESTDIR}/tftpboot/systemimager/
cp -p ${DESTDIR}/etc/hosts . || true > hosts

# gotta make sure the masses can read it...
chmod a+r hosts

# copy tftpstuff into tftp area
for TFTP_ITEM in `ls $INSTALL_DIR/tftpstuff/ | grep -wv CVS`
do
  cp -af $INSTALL_DIR/tftpstuff/$TFTP_ITEM ${DESTDIR}/tftpboot/
  [ "x$DESTDIR" = "x" ] && chown -R root:root ${DESTDIR}/tftpboot/$TFTP_ITEM
  (test -d $TFTP_ITEM && cd ${DESTDIR}/tftpboot/$TFTP_ITEM && find . -name CVS -exec rm -rf {} \;) >/dev/null 2>&1
done

# turns out we *can* actually use the exact same config file -- Thanks, H.P. Anvin ;)
cd ${DESTDIR}/tftpboot/pxelinux.cfg/
ln -f syslinux.cfg default
### END tftpboot stuff ###


### BEGIN images stuff ###

# create ${DESTDIR}/var/spool/systemimager
mkdir -p ${DESTDIR}/var/spool/systemimager/images
chmod 750 ${DESTDIR}/var/spool/systemimager/images

# Create Warning file
cat > ${DESTDIR}/var/spool/systemimager/images/README <<EOF
#
# "SystemImager" - Copyright (C) 1999-2000 Brian Elliott Finley <brian@valinux.com>
#

***GOTCHA!***

DO NOT TOUCH THESE DIRECTORIES UNLESS YOU KNOW EXACTLY WHAT YOU ARE DOING!!!

You have the ability to totally hose an entire network of computers if you put
the wrong file in the right place.  OR EVEN MESS UP THE PERMISSIONS ON A FILE.

Permissions, ownership, modes, sticky-bits, etc. are all very important as they
will be replicated *exactly* on the clients!!!
EOF

# Create extra scary link to warning file
cd ${DESTDIR}/var/spool/systemimager/images
ln -sf README DO_NOT_TOUCH_THESE_DIRECTORIES

### END images stuff ###


### BEGIN documentation and what not stuff ###

# Documentation -- copy BIG CASE files
# (RPM will take care of docs for us)
if [ "x$DESTDIR" = "x" ]; then
  rm -fr ${prefix}/doc/systemimager-*
  mkdir -p ${prefix}/doc/systemimager-$VERSION/
  cp -af $INSTALL_DIR/[A-Z]* ${prefix}/doc/systemimager-$VERSION/
  chown -R root:root ${prefix}/doc/systemimager-$VERSION/
fi

### END documentation and what not stuff ###


# run afterburner unless told otherwise...
if [ "$AFTERBURNER" = "yes" ]; then
  [ $QUIET = "false" ] && $INSTALL_DIR/afterburner --non-interactive || $INSTALL_DIR/afterburner --non-interactive --quiet
fi

exit 0
