#!/bin/sh

# 
# 2010.10.30 Brian Elliott Finley
# - Created by combining the upstart event bits from an Ubuntu Lucid
#   machine.
#

# udev - device node and kernel event manager
#
# The udev daemon receives events from the kernel about changes in the
# /sys filesystem and manages the /dev filesystem.
#
/lib/udev/udevd --daemon
# -BEF: Use for debug- /sbin/udevd --daemon --debug >/tmp/udevd.log 2>&1

# udevtrigger - cold plug devices
#
# By the time udevd starts, we've already missed all of the events for
# the devices populated in /sys.  This task causes the kernel to resend
# them.
#
/usr/bin/udevadm trigger

# udevmonitor - log initial device creation
#
# The set of devices created in the "cold plug" pass is generally
# useful for debugging, so we monitor this and create a log file
# from that.
#
/usr/bin/udevadm monitor -e >/dev/.udev.log &

# udev-finish - save udev log and update rules
#
# While udev runs we not only create the log file of initial device
# creation but udev rules may be generated, we need to copy both of
# these out of /dev and onto the root filesystem.
#
# Save udev log in /var/log/udev
#
if [ -e /dev/.udev.log ]
then
mv -f /dev/.udev.log /var/log/udev || :
fi

# Copy any rules generated while the root filesystem was read-only
for file in /dev/.udev/tmp-rules--*
do
[ -e "$file" ] || continue
cat "$file" >> "/etc/udev/rules.d/${file##*tmp-rules--}"
rm -f "$file"
done

