#!/usr/bin/perl -w

#
# "SystemImager" - Copyright (C) 1999-2000 TheFinleys.com <brian@thefinleys.com> 
#
# This file is: /systemimager/bin/makedhcpserver
#

# Subroutines
sub get_response {
 my $garbage_out=$_[0];
 my $garbage_in=<STDIN>;
 chomp $garbage_in;
 unless($garbage_in eq "") { $garbage_out = $garbage_in; }
 return $garbage_out;
}

# if not run as root, this script will surely fail
unless($< == 0) { die "Must be run as root!\n"; }

system("clear");

# give warning
print <<"EOF";

Welcome to the SystemImager "makedhcpserver" script.  This script 
will prepare this computer to be a DHCP server by creating
the following file:

 /etc/dhcpd.conf

If there is an existing file, it will be backed up with the 
.beforesystemimager extension.

EOF

print "Continue? (y/[n]): ";
$continue=<STDIN>;
chomp $continue;
($continue eq "y") or die "\nmakedhcpd: No files were modified.\n";

# backup dhcpd.conf if necessary
if( -e "/etc/dhcpd.conf" && ! -e "/etc/dhcpd.conf.beforesystemimager") { 
 rename("/etc/dhcpd.conf", "/etc/dhcpd.conf.beforesystemimager");
}

# set some default values
$dnsdomainname="";
$netnumber = "192.168.1.0";
$netmask = "255.255.255.0";
$rangebegin = "192.168.1.50";
$rangeend = "192.168.1.100";
$dnsserver1 = "";
$dnsserver2 = "";
$dnsserver3 = "192.168.1.1";
$router = "192.168.1.1";
$swallow = "";

### Begin questionnaire ###
$satisfied = "n";
while ($satisfied ne "y") {
 system("clear");
 print "Type your response or hit <Enter> to accept [defaults].\n";

 print "If you don't have a response, such as no first or second DNS server,\n";
 print "just hit <Enter> and none will be used.\n";

 print "\nWhat is your domain name? [$dnsdomainname]: ";
 $dnsdomainname=get_response($dnsdomainname);

 print "What is your network number? [$netnumber]: ";
 $netnumber=get_response($netnumber);

 print "What is your netmask? [$netmask]: ";
 $netmask=get_response($netmask);

 print "What is the starting IP address for your dhcp range? [$rangebegin]: ";
 $rangebegin=get_response($rangebegin);

 print "What is the ending IP address for your dhcp range? [$rangeend]: ";
 $rangeend=get_response($rangeend);

 print "What is the IP address of your first DNS server? [$dnsserver1]: ";
 $dnsserver1=get_response($dnsserver1);

 print "What is the IP address of your second DNS server? [$dnsserver2]: ";
 $dnsserver2=get_response($dnsserver2);

 print "What is the IP address of your third DNS server? [$dnsserver3]: ";
 $dnsserver3=get_response($dnsserver3);

 print "What is the IP address of your default gateway? [$router]: ";
 $router=get_response($router);

 print "What is the air speed velocity of the common swallow? [$swallow]: ";
 $swallow=<STDIN>;
 system("clear");
 chomp $swallow;
 $swallow = lc $swallow;
 if($swallow =~ /african/) {
  print "Aaaaaaaaaaaaaaaaaaaaaaaaaaaah!\n";
 } else {
  print "Wrong!!! (with a Monty Python(TM) accent...)\n";
 }
 print "\nPress <Enter> to continue...";
 $pause=<STDIN>;

 system("clear");
 print "Ahh, but seriosly folks...\n";
 print "Here are the values you have chosen:\n\n";
 print "################################################################\n";
 print "DNS Domain Name: $dnsdomainname\n";
 print "network number:  $netnumber\n";
 print "netmask:         $netmask\n";
 print "starting IP address for your dhcp range: $rangebegin\n";
 print "ending IP address for your dhcp range:   $rangeend\n";
 print "first DNS server:  $dnsserver1\n";
 print "second DNS server: $dnsserver2\n";
 print "third DNS server:  $dnsserver3\n";
 print "default gateway: $router\n";
 print "################################################################\n";
 
 print "\nAre you satisfied? (y/[n]): ";
 $satisfied=<STDIN>;
 chomp $satisfied;
}
### End questionnaire ###

# open /etc/dhcpd.conf for writing
open(DHCPDCONF, "> /etc/dhcpd.conf") or die "Couldn't open /etc/dhcpd.conf for writing: $!\n";

print DHCPDCONF qq(subnet $netnumber netmask $netmask { \n);
print DHCPDCONF qq(  range  $rangebegin $rangeend; \n);
print DHCPDCONF qq(  option domain-name "$dnsdomainname"; \n);
print DHCPDCONF qq(  option domain-name-servers );
if($dnsserver1 ne "") { print DHCPDCONF qq($dnsserver1); }
if($dnsserver2 ne "") { print DHCPDCONF qq(, $dnsserver2); }
if($dnsserver3 ne "") { print DHCPDCONF qq(, $dnsserver3); }
print DHCPDCONF qq(;\n);
print DHCPDCONF qq(  option routers $router; \n);
print DHCPDCONF qq(} \n);

close(DHCPDCONF);

# touch dhcpd.leases file(s) so that dhcpd won't fart when started
# different RPM installs put the file in different places so we touch
# one of two files and a monkey
if( ! -e "/var/state/dhcp") {system("touch /etc/dhcpd.leases");}
if( -e "/var/state/dhcp" ) {system("touch /var/state/dhcp/dhcpd.leases");}

# words of wisdom
system("clear");
print <<"EOF";

The dhcp server configuration file (/etc/dhcpd.conf) file has been created 
for you.  Please verify it for accuracy.  The imageserver's IP address 
should be listed as the last domain-name-servers entry.

If this file does not look satisfactory, you can run this script again to 
re-create it: "/systemimager/bin/makedhcpserver"

WARNING!:  If you have multiple physical network interfaces, be sure to 
edit the init script that starts dhcpd so that it looks like: 
"dhcpd \$interfacename"
( ie. /sbin/dhcpd eth0 )

Also, be sure to start or restart your dhcpd daemon. 
( ie. /etc/rc.d/init.d/dhcpd restart )

EOF

print "Press <Enter> to continue...";
$pause=<STDIN>;
