#!/usr/bin/perl -w
#
# "SystemImager" - Copyright (C) 1999-2000 TheFinleys.com <brian@thefinleys.com> 
#
# /systemimager/bin/makedhcpstatic
#

# if not run as root, this script will surely fail
unless($< == 0) { die "Must be run as root!\n"; }

#FIX# give warning
#if -q then no warning

# read in /etc/dhcpd.conf
open(DHCPDCONF, "< /etc/dhcpd.conf") or die "Couldn't open /etc/dhcpd.conf for reading: $!\n";
while (<DHCPDCONF>) { push(@dhcpdconf, $_); }
close(DHCPDCONF);

# test for /var/state/dhcp/dhcpd.leases (newest and preferred location)
if(-e "/var/state/dhcp/dhcpd.leases") {
  $dhcpd_leases = "/var/state/dhcp/dhcpd.leases";
  # read in dhcpd.leases and create an IP/mac address hash
  %ipbymac = ();
  open(LEASEINFO, "< $dhcpd_leases") or die "Couldn't open $dhcpd_leases for reading: $!\n";
  $line = "";
  while(<LEASEINFO>) {
    chomp;
    # get rid of tabs (not a normal space --> <ctrl>+<v> then <tab> )
    $_ =~ s/    //;
    $_ =~ s/;/ /;
    if ( /^#/ )     { next; }
    elsif( ! /}/ )  { $line = $line . $_; }
    else            {
      $line = $line . $_;
      my @fields = split(/ /, $line);
      $ipbymac{$fields[12]} = $fields[1];
      $line = "";
    }
  }
  close(LEASEINFO);
} 

# test for /etc/dhcpd.leases
elsif( -e "/etc/dhcpd.leases" ) {
  $dhcpd_leases = "/etc/dhcpd.leases";
  # read in dhcpd.leases and create an IP/mac address hash
  %ipbymac = ();
  open(LEASEINFO, "< $dhcpd_leases") or die "Couldn't open $dhcpd_leases for reading: $!\n";
  $line = "";
  while(<LEASEINFO>) {
    chomp;
    # get rid of tabs (not a normal space --> <ctrl>+<v> then <tab> )
    $_ =~ s/    //;
    $_ =~ s/;/ /;
    if ( /^#/ )     { next; }
    elsif( ! /}/ )  { $line = $line . $_; }
    else            {
      $line = $line . $_;
      my @fields = split(/ /, $line);
      $ipbymac{$fields[12]} = $fields[1];
      $line = "";
    }
  }
  close(LEASEINFO);
}


# default to using info in /var/log/messages
else {
  # read in /var/log/messages and create an IP/mac address hash
  %ipbymac = ();
  open(LEASEINFO, "< /var/log/messages") or die "Couldn't open /var/log/messages for reading: $!\n";
  while (<LEASEINFO>) {
    if (/DHCPACK/) {
      my @fields = split;
      $ipbymac{$fields[9]} = $fields[7];
    }
  }
  close(LEASEINFO);
}

# read in /etc/hosts and create an IP address/host name hash
%hostsbyip = ();
open(HOSTS, "< /etc/hosts") or die "Couldn't open /etc/hosts for reading: $!\n";
while (<HOSTS>) {
  if (/^\s*\d+\.\d+\.\d+\.\d+\s+\w/) {	# match a non-commented IP/hostname entry
    my @fields = split;
    $hostsbyip{$fields[0]} = $fields[1]; }
}
close(HOSTS);

# open /etc/dhcpd.conf for writing
open(DHCPDCONF, ">> /etc/dhcpd.conf") or die "Couldn't open /etc/dhcpd.conf for appending: $!\n";
#FIX# need to add section for testing to see if IP is already assigned (and sort there instead ;)...
@macs = sort (keys %ipbymac);
foreach $mac (@macs) {
  $exists="no";
  foreach(@dhcpdconf) { 
    if(/$mac/) { 
      $exists="yes";
      last;
    } 
  }
  # update dhcpd.conf as necessary
  #FIX# need to remove fixed addresses from range -- test to be sure, but I believe hosts that
  # are already in dhcpd.leases, or hosts that have a MAC specified will continue to get the 
  # appropriate address, but if a _new_ host boots, it may get an address from the range that
  # is actually reserved for a specific MAC address.  -- must test -- <bef>
  unless($exists eq "yes") { 
    # autoinstall client gets it's hostname from hosts file pulled from $imageserver::etc/hosts
    #  that's how it knows which script file to pull
    #
    $hostname = $hostsbyip{$ipbymac{$mac}};
    print "Adding entry for $hostname:\t$mac $ipbymac{$mac} to /etc/dhcpd.conf\n";
    print DHCPDCONF qq(host $hostname { hardware ethernet $mac; fixed-address $hostname; }\n);
  }
}
close(DHCPDCONF);
