#!/usr/bin/perl -w

#
# "SystemImager" - Copyright (C) 1999-2001 Brian Elliott Finley <brian@systemimager.org>
#
#   $Id$
#
#   Written by Brian Elliott Finley <brian@systemimager.org>
#

print <<'EOF';

makeautoinstalldiskette has been renamed to 
  "mkautoinstalldiskette"

EOF
exit 1
