#!/bin/sh

#
# "VA SystemImager" - Copyright (C) 1999-2000 Brian Elliott Finley <brian@systemimager.org>
#
# This file is: mk_manual
#
# I use this script to produce the manual html from the source sgml file
#

rm -fr manual
rm -fr ../manual
db2html manual.sgml
cp -a images/ manual/images
mv manual ..
echo
echo
echo "You can now find the manual in <source>/doc/manual/"
echo "  (also known as ../manual)"
