#!/bin/bash

# inst_multiple only available in future fersions.
inst_multiple() {
    dracut_install "$@"
}

install() {
    # Copy systemimager template
    (cd @@SIS_INITRD_TEMPLATE@@; tar cpf - .)|(cd $initdir; tar xpf -)
    # binaries we want in initramfs
    inst_multiple -o mke2fs mkfs.ext2 mkfs.ext3 mkfs.ext4 mklost+found resize2fs tune2fs e2fsck mkfs.xfs
    inst_multiple -o dosfsck dosfslabel fatlabel fsck.fat fsck.msdos fsck.vfat mkdosfs mkfs.fat mkfs.msdos mkfs.vfat
    #inst_multiple fsck.hfs hattrib hcd hcopy hdel hdir hformat hfs hfsck hls hmkdir hmount hpwd hrename hrmdir humount hvol
    inst_multiple -o btrfs btrfsck btrfstune fsck.btrfs mkfs.btrfs
    inst_multiple cut date echo env sort test false true [ expr head install tail tee tr uniq wc tac
    # inst_multiple setfont loadkeys kbd_mode stty # i18n module
    inst_multiple bc gzip bzip2 rsync parted blockdev awk ncat tty killall kexec ipcalc findmnt
    inst_multiple depmod blkid
    # Some helpfull command in case of problem
    inst_multiple find strace sysctl vi clear reset
    inst_multiple chmod chown cp dd df dmesg echo egrep fdisk fgrep grep halt hostname ifconfig init insmod kill ln ls lsmod mkdir mknod mkswap modprobe more mv ping poweroff ps reboot shutdown rm rmdir rmmod route sed sh sleep swapoff swapon sync tar touch uname

    inst "$moddir/systemimager-lib.sh" "/lib/systemimager-lib.sh"
    inst "$moddir/autoinstall-lib.sh" "/lib/autoinstall-lib.sh"
    inst_script "$moddir/systemimager-load-dhcpopts.sh" "/sbin/systemimager-load-dhcpopts"
    inst_script "$moddir/systemimager-netstart-old.sh" "/sbin/systemimager-netstart"
    inst_script "$moddir/systemimager-start.sh" "/sbin/systemimager-start"
    inst_script "$moddir/systemimager-pingtest.sh" "/sbin/systemimager-pingtest"
    inst_script "$moddir/systemimager-monitor-server.sh" "/sbin/systemimager-monitor-server"
    inst_script "$moddir/systemimager-deploy-client.sh" "/sbin/systemimager-deploy-client"
    # We need to overwrite 40network dhclient-script with our version that handles /etc/dhcp/dhclient-exit-hooks
    inst_hook cmdline 10 "$moddir/restore-persistent-cmdline.d.sh" # copy /etc/persistent-cmdline.d to /etc/cmdline.d/
    inst_hook cmdline 20 "$moddir/parse-i18n.sh" # rd.vconsole.* parameters are not parsed if dracut uses systemd (upstream BUG)
    inst_hook cmdline 50 "$moddir/parse-sis-options-old.sh" # read cmdline parameters
    inst_hook cmdline 70 "$moddir/parse-local-cfg.sh" # read local.cfg and overrides cmdline
    inst_hook initqueue-settled  50 "$moddir/systemimager-init.sh" # Creates /run/systemimager
    inst_hook initqueue-finished 90 "$moddir/systemimager-wait-imaging.sh" # Waits for file /tmp/SIS_action
    inst_hook initqueue-timeout 10 "$moddir/systemimager-timeout.sh" # In case of timeout (DHCP failure, ....)
    inst_hook pre-udev 10 "$moddir/systemimager-genrules.sh" # needed because lack of initqueue-online

    # dracut_need_initqueue
}

install
