#!/bin/bash
#
# "SystemImager" 
#
#  Copyright (C) 1999-2017 Brian Elliott Finley <brian@thefinleys.com>
#
#  $Id$
#  vi: set filetype=sh et ts=4:
#
#  Code written by Olivier LAHAYE.
#
# This file is part of the old dracut distro. It is used to check dependancies
# for systemimager dracut module

# Require network.
[ "$1" = "-d" ] && echo network shutdown i18n

# hostonly check: does not work in host only mode.
[ "$1" = "-h" ] && exit 1

# do not add this module by default
exit 255
