#!/bin/bash

# Require network.
[ "$1" = "-d" ] && echo network syslog shutdown i18n

# hostonly check: does not work in host only mode.
[ "$1" = "-h" ] && exit 1

# do not add this module by default
exit 255
