#!/bin/bash
#
# "SystemImager"
#
#  Copyright (C) 1999-2017 Brian Elliott Finley <brian@thefinleys.com>
#
#  $Id$
#  vi: set filetype=sh et ts=4:
#
#  Code written by Olivier LAHAYE.
#
# This file is the systemimager main old dracut module setup file.

# inst_multiple only available in future fersions.
inst_multiple() {
    dracut_install "$@"
}

install() {
    # 1/ Copy systemimager template
    (cd ${SI_INITRD_TEMPLATE:=/usr/share/systemimager/boot/$(uname -m)/standard/initrd_template/}; tar cpf - .)|(cd $initdir; tar xpf -)

    # 2/ Install binaries we need.
    # Filesystems we want to be able to handle
    inst_multiple -o mkfs.xfs xfs_admin xfs_repair
    inst_multiple -o mkfs.ext4 mkfs.ext3 mkfs.ext2 mke2fs tune2fs resize2fs tune2fs
    inst_multiple -o mkfs.fat mkfs.msdos mkfs.vfat mkfs.ntfs mkdosfs dosfslabel fatlabel
    inst_multiple -o mkfs.btrfs btrfs btrfstune
    inst_multiple -o mkfs.reiserfs mkreiserfs reiserfstune resize_reiserfs tunefs.reiserfs
    inst_multiple -o mkfs.jfs jfs_mkfs jfs_tune
    inst_multiple -o mklost+found # Do we need that?
    inst_multiple -o socat # plymouth ask-for-password replacement requirement (CentOS-7 at least)
    # Install ssh and its requirements
    install_ssh
    # Install docker and its requirements
    install_docker
    # Install plymouth theme and its requirements
    install_plymouth_theme
    inst_multiple cut date echo env sort test false true [ expr head install tail tee tr uniq wc tac mktemp yes xmlstarlet
    # inst_multiple setfont loadkeys kbd_mode stty # i18n module
    inst_multiple bc dc gzip bzip2 rsync mkfs parted sgdisk fdisk blockdev lsblk partprobe awk ncat tty killall kexec ipcalc findmnt findfs tput stty
    inst_multiple lvm pvcreate pvdisplay pvremove pvscan lvcreate lvdisplay lvremove lvscan lvmconf lvmconfig lvmdump lvchange vgcreate vgdisplay vgremove vgscan fsadm
    inst_multiple chmod chown cp dd df dmesg echo egrep fgrep grep halt host hostname ifconfig init insmod kill ln ls lsmod mkdir mknod mkswap modprobe more mv ping poweroff ps reboot shutdown rm rmdir rmmod route sed sh sleep swapoff swapon sync tar touch uname logger od socat
    inst_multiple uuidgen
    inst_multiple depmod blkid
    # Some helpfull command in case of problem
    inst_multiple -o find strace sysctl vi clear reset lsof fuser
    # bittorent client needed when using bittorrent deployment method.
    inst_multiple rtorrent

    # 3/ Install dracut logic
    inst "$moddir/systemimager-lib.sh" "/lib/systemimager-lib.sh"
    inst "$moddir/autoinstall-lib.sh" "/lib/autoinstall-lib.sh"
    inst "$moddir/disksmgt-lib.sh" "/lib/disksmgt-lib.sh"
    inst "$moddir/systemimager-install-rebooted-script.sh" "/lib/systemimager-install-rebooted-script"
    inst "$moddir/si_inspect_client.sh" "/sbin/si_inspect_client"
    for protocol_plugin in $moddir/systemimager-xmit-*.sh
    do
        inst "$protocol_plugin" "/lib/${protocol_plugin##*/}"
    done
    mkdir -p $initdir/usr/lib/systemimager/
    inst "$moddir/do_partitions.xsl" "/lib/systemimager/do_partitions.xsl" # Installs partition xml transformation filter
    inst "$moddir/disks-layout.xsd" "/lib/systemimager/disks-layout.xsd" # Installs disks layout validation schem.
    inst_script "$moddir/systemimager-load-network-infos.sh" "/sbin/systemimager-load-network-infos"
    inst_script "$moddir/systemimager-load-scripts-ecosystem.sh" "/sbin/systemimager-load-scripts-ecosystem"
    inst_script "$moddir/systemimager-netstart-old.sh" "/sbin/systemimager-netstart"
    inst_script "$moddir/systemimager-start.sh" "/sbin/systemimager-start"
    inst_script "$moddir/systemimager-pingtest.sh" "/sbin/systemimager-pingtest"
    inst_script "$moddir/systemimager-monitor-server.sh" "/sbin/systemimager-monitor-server"
    inst_script "$moddir/systemimager-deploy-client.sh" "/sbin/systemimager-deploy-client"
    inst_script "$moddir/parse-local-cfg.sh" "/sbin/parse-local-cfg"
    inst_hook cmdline 30 "$moddir/systemimager-check-kernel.sh" # Check that kernel & initrd match.
    inst_hook cmdline 50 "$moddir/parse-systemimager.sh" # read cmdline parameters
    inst_hook cmdline 70 "$moddir/systemimager-init.sh" # Creates /run/systemimager and sets rootok
    inst_hook initqueue-settled  50 "$moddir/systemimager-warmup.sh" # Waits for plymouth
    inst_hook initqueue-finished 90 "$moddir/systemimager-wait-imaging.sh" # Waits for $SI_IMAGING_STATUS = "finished"
    inst_hook initqueue-timeout 10 "$moddir/systemimager-timeout.sh" # In case of timeout (DHCP failure, ....)
    inst_hook mount 98 "$moddir/systemimager-sysroot-helper.sh" # read root infos so next script can mount /sysroot
    inst_hook pre-udev 10 "$moddir/systemimager-genrules.sh" # needed because lack of initqueue-online
    inst_hook pre-pivot 90 "$moddir/systemimager-cleanup.sh" # Clean any remaining systemimager remaining stuffs (cleanup hook not available in old dracut)

    # 4/ Install workaround
    # workaround for bug https://bugs.centos.org/view.php?id=13357
    inst "/lib/udev/console_check" "/lib/udev/console_check"

    # dracut_need_initqueue
}

################################################################################
# sub routine that installs ssh
#
install_ssh() {
    # Install binaries
    inst_multiple -o ssh scp ssh-keygen sshd wget
    # Install clients config
    (cd /etc; tar cpf - ssh/ssh_config*)|(cd $initdir/etc; tar xpf -)
    # Install server config
    (cd /etc; tar cpf - ssh/sshd_config ssh/moduli)|(cd $initdir/etc; tar xpf -)
    # Disable PAM authentication.
    sed -i -e 's/^UsePAM\syes/UsePAM no/g' $initdir/etc/ssh/sshd_config
}

################################################################################
# sub routine that installs docker client
#
install_docker() {
    # Install binaries
    inst_multiple -o docker docker-current
    # Install clients config
    (cd /etc; test -f docker/seccomp.json && tar cpf - docker/seccomp.json)|(cd $initdir/etc; tar xpf -)
    # Install system docker config.
    [ -f /etc/sysconfig/docker ] && mkdir -p $initdir/etc/sysconfig && cp /etc/sysconfig/docker $initdir/etc/sysconfig
    [ -f /etc/default/docker ] && mkdir -p $initdir/etc/default && c /etc/default/docker $initdir/etc/default
}

################################################################################
# sub routine that installs plymouth theme
#
install_plymouth_theme() {
    # Install minimal plymouth support
    PLUGINDIR=`plymouth --get-splash-plugin-path`
    inst ${PLUGINDIR}/script.so $initdir
    inst ${PLUGINDIR}/label.so $initdir
    inst /usr/share/plymouth/themes/text/text.plymouth $initdir
    inst /usr/share/plymouth/themes/details/details.plymouth $initdir

    # Install required fonts and coonfig file.
    inst /usr/share/fonts/dejavu/DejaVuSerif.ttf $initdir
    inst /usr/share/fonts/dejavu/DejaVuSans.ttf $initdir
    inst /etc/fonts/fonts.conf $initdir # fontconfig lib used by plymouth requires it.

    # Install systemimager plymouth theme
    mkdir -p $initdir/usr/share/plymouth/themes/systemimager
    cp $moddir/plymouth_theme/{*.png,systemimager.plymouth,systemimager.script} $initdir/usr/share/plymouth/themes/systemimager
    ( cd ${initdir}/usr/share/plymouth/themes; ln -sf systemimager/systemimager.plymouth default.plymouth 2>&1 )
    mkdir -p ${initdir}/etc/plymouth/
    cat > ${initdir}/etc/plymouth/plymouthd.conf <<EOF
# SystemImager is the default theme
[Daemon]
Theme=systemimager
ShowDelay=0
# DeviceTimeout=5
EOF
    cp -f ${initdir}/etc/plymouth/plymouthd.conf ${initdir}/usr/share/plymouth/plymouthd.defaults
}

install
