#!/bin/bash
#
# "SystemImager"
#
#  Copyright (C) 1999-2017 Brian Elliott Finley <brian@thefinleys.com>
#
#  $Id$
#  vi: set filetype=sh et ts=4:
#
#  Code written by Olivier LAHAYE.
#
# This file is the systemimager main old dracut module setup file.

# inst_multiple only available in future fersions.
inst_multiple() {
    dracut_install "$@"
}

install() {
    # 1/ Copy systemimager template
    (cd @@SIS_INITRD_TEMPLATE@@; tar cpf - .)|(cd $initdir; tar xpf -)

    # 2/ Install binaries we need.
    # Filesystems we want to be able to handle
    inst_multiple -o mkfs.xfs
    inst_multiple -o mkfs.ext4 mkfs.ext3 mkfs.ext2 mke2fs tune2fs resize2fs
    inst_multiple -o mkfs.fat mkfs.msdos mkfs.vfat mkfs.ntfs mkdosfs dosfslabel fatlabel
    inst_multiple -o mkfs.btrfs btrfs btrfstune
    inst_multiple -o mkfs.reiserfs mkreiserfs reiserfstune resize_reiserfs tunefs.reiserfs
    inst_multiple -o mkfs.jfs jfs_mkfs jfs_tune
    inst_multiple -o mklost+found # Do we need that?
    # Install ssh and its requirements
    install_ssh
    # Install plymouth theme and its requirements
    install_plymouth_theme
    inst_multiple cut date echo env sort test false true [ expr head install tail tee tr uniq wc tac mktemp yes xmlstarlet
    # inst_multiple setfont loadkeys kbd_mode stty # i18n module
    inst_multiple bc gzip bzip2 rsync mkfs parted pvcreate blockdev lsblk partprobe awk ncat tty killall kexec ipcalc findmnt tput stty
    inst_multiple chmod chown cp dd df dmesg echo egrep fdisk fgrep grep halt host hostname ifconfig init insmod kill ln ls lsmod mkdir mknod mkswap modprobe more mv ping poweroff ps reboot shutdown rm rmdir rmmod route sed sh sleep swapoff swapon sync tar touch uname logger
    inst_multiple depmod blkid
    # Some helpfull command in case of problem
    inst_multiple -o find strace sysctl vi clear reset lsof fuser

    # 3/ Install dracut logic
    inst "$moddir/systemimager-lib.sh" "/lib/systemimager-lib.sh"
    inst "$moddir/autoinstall-lib.sh" "/lib/autoinstall-lib.sh"
    inst "$moddir/si_inspect_client.sh" "/sbin/si_inspect_client"
    for protocol_plugin in $moddir/systemimager-xmit-*.sh
    do
        inst "$protocol_plugin" "/lib/${protocol_plugin##*/}"
    done
    inst_script "$moddir/systemimager-load-dhcpopts.sh" "/sbin/systemimager-load-dhcpopts"
    inst_script "$moddir/systemimager-load-config.sh" "/sbin/systemimager-load-config"
    inst_script "$moddir/systemimager-netstart-old.sh" "/sbin/systemimager-netstart"
    inst_script "$moddir/systemimager-start.sh" "/sbin/systemimager-start"
    inst_script "$moddir/systemimager-pingtest.sh" "/sbin/systemimager-pingtest"
    inst_script "$moddir/systemimager-monitor-server.sh" "/sbin/systemimager-monitor-server"
    inst_script "$moddir/systemimager-deploy-client.sh" "/sbin/systemimager-deploy-client"
    inst_hook cmdline 01 "$moddir/init-cmdline.sh" # copy /etc/persistent-cmdline.d to /etc/cmdline.d/
    #inst_hook cmdline 20 "$moddir/parse-i18n.sh" # rd.vconsole.* parameters are not parsed if dracut uses systemd (upstream BUG)
    inst_hook cmdline 30 "$moddir/systemimager-check-kernel.sh" # Check that kernel & initrd match.
    inst_hook cmdline 50 "$moddir/parse-sis-options-old.sh" # read cmdline parameters
    inst_hook cmdline 70 "$moddir/parse-local-cfg.sh" # read local.cfg and overrides cmdline
    inst_hook initqueue-settled  50 "$moddir/systemimager-init.sh" # Creates /run/systemimager
    inst_hook initqueue-finished 90 "$moddir/systemimager-wait-imaging.sh" # Waits for file /tmp/SIS_action
    inst_hook initqueue-timeout 10 "$moddir/systemimager-timeout.sh" # In case of timeout (DHCP failure, ....)
    inst_hook pre-udev 10 "$moddir/systemimager-genrules.sh" # needed because lack of initqueue-online

    # 4/ Install workaround
    # workaround for bug https://bugs.centos.org/view.php?id=13357
    inst "/lib/udev/console_check" "/lib/udev/console_check"

    # dracut_need_initqueue
}

################################################################################
# sub routine that installs ssh
#
install_ssh() {
    # Install binaries
    inst_multiple -o ssh scp ssh-keygen sshd wget
    # Install clients config
    (cd /etc; tar cpf - ssh/ssh_config*)|(cd $initdir/etc; tar xpf -)
    # Install server config
    (cd /etc; tar cpf - ssh/sshd_config ssh/moduli)|(cd $initdir/etc; tar xpf -)
    # Disable PAM authentication.
    sed -i -e 's/^UsePAM\syes/UsePAM no/g' $initdir/etc/ssh/sshd_config
}

################################################################################
# sub routine that installs plymouth theme
#
install_plymouth_theme() {
    PLUGINDIR=`plymouth --get-splash-plugin-path`
    inst ${PLUGINDIR}/script.so $initdir
    inst ${PLUGINDIR}/label.so $initdir
    # Cleanup unwanted themes
    ( cd $initdir/usr/share/plymouth/themes/
        for THEME in `echo *|sed -r 's/\stext|\sdetails//g'`
       	do
            rm -rf $initdir/usr/share/plymouth/themes/$THEME # Remove unwanted themes
        done
    )
    # Install required fonts and coonfig file.
    inst /usr/share/fonts/dejavu/DejaVuSerif.ttf $initdir
    inst /usr/share/fonts/dejavu/DejaVuSans.ttf $initdir
    inst /etc/fonts/fonts.conf $initdir # fontconfig lib used by plymouth requires it.

    # Install systemimager plymouth theme
    mkdir -p $initdir/usr/share/plymouth/themes/systemimager
    cp $moddir/plymouth_theme/{*.png,systemimager.plymouth,systemimager.script} $initdir/usr/share/plymouth/themes/systemimager
    ( cd ${initdir}/usr/share/plymouth/themes; ln -sf systemimager/systemimager.plymouth default.plymouth 2>&1 )
    cat > ${initdir}/etc/plymouth/plymouthd.conf <<EOF
# SystemImager is the default theme
[Daemon]
Theme=systemimager
ShowDelay=0
DeviceTimeout=5
EOF
}

install
