#!/bin/sh

#
# "VA SystemImager" - Copyright (C) 1999-2000 Brian Elliott Finley <brian@systemimager.org>
#
# This file is: mk_new_initrd
#
# I use this script to produce the initrd.gz from the stuff I put into initrd_dev
#


# if not run as root, will surely fail
if [ `whoami` != "root" ]
then
    echo "Must be run as root!"
    exit 1
fi


DATE=`date +%Y.%m.%d-%H:%M:%S`

chown -R root.root initrd_dev

cd initrd_dev \
  && /usr/src/boot-floppies/scripts/rootdisk/mklibs.sh -v -d lib bin/*

cd .. \
  && dd if=/dev/zero of=initrd2 bs=1k count=2000 && echo 'y' | mke2fs -N 584 -m 0 initrd2 \
  && mkdir -p initrd2.dir \
  && mount -o loop initrd2 initrd2.dir/ \
  && ( cd initrd_dev/ ; tar -cvf - * ) | tar -C initrd2.dir/ -xv \
  && umount initrd2 \
  && rmdir initrd2.dir \
  && gzip -9 initrd2 \
  && mv initrd2.gz initrd-${DATE}.gz \
  && ls -l initrd-${DATE}.gz /tftpboot/initrd.gz
