#!/bin/sh

#
# "VA SystemImager" - Copyright (C) 1999-2000 Brian Elliott Finley <brian@systemimager.org>
#
# This file is: mk_new_initrd
#
# I use this script to produce the initrd.gz from the stuff I put into initrd_dev
#


# if not run as root, will surely fail
if [ `whoami` != "root" ]
then
    echo "Must be run as root!"
    exit 1
fi

### functions ###

# Example usage
#execute "ls one two three four five six seven eight"
execute() {
  COMMAND=$1
  echo
  echo $COMMAND
  $COMMAND || {
               echo
	       echo FATAL: $COMMAND failed!!!
               exit 1
	      }
}

DATE=`date +%Y.%m.%d-%H:%M:%S`

execute "chown -R root.root initrd_dev"

execute "cd initrd_dev "

execute "/usr/src/boot-floppies/scripts/rootdisk/mklibs.sh -v -d lib bin/* "

execute "cd .. "

execute "umount initrd2"

execute "dd if=/dev/zero of=initrd2 bs=1k count=2000"

execute "echo 'y' | mke2fs -N 584 -m 0 initrd2 "

execute "mkdir -p initrd2.dir "

execute "mount -o loop -t ext2 initrd2 initrd2.dir/ "

execute "( cd initrd_dev/ ; tar -cvf - * ) | tar -C initrd2.dir/ -xv "

execute "[ -d ./initrd2.dir/lost+found/ ] && umount initrd2 "

execute "rmdir initrd2.dir "

execute "gzip -9 initrd2 "

execute "mv initrd2.gz initrd-${DATE}.gz "

execute "ls -l initrd-${DATE}.gz /tftpboot/initrd.gz "

